title: Gobinda Saha
logo: /assets/Images/profile_pic_circle.png
description: Lifelong learning, Meta-learning, Online learning, Transfer and multitask Learning
# show_downloads: true
theme: jekyll-theme-minimal
