title: Gobinda Saha
logo: /assets/Images/profile_pic_circle.png
description: Deep learning optimization, Lifelong learning, Meta-learning, Online learning, Transfer and multitask learning
# show_downloads: true
theme: jekyll-theme-minimal
